plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'lk.jiat.agrolink'
    compileSdk 36

    defaultConfig {
        applicationId "lk.jiat.agrolink"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures{
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.firebase.messaging
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation platform(libs.firebase.bom)
    implementation libs.google.firebase.analytics
    implementation libs.google.firebase.auth
    implementation libs.google.firebase.firestore
    implementation libs.google.firebase.storage
    implementation libs.firebase.database
    implementation libs.google.firebase.messaging
    implementation libs.picasso
    implementation libs.recyclerview
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.okhttp.logging
    implementation libs.osmdroid // ✅ මෙතනට osm එක් කළා
    implementation libs.play.services.location
    implementation libs.play.services.maps
}
